repos:
-   repo: local
    hooks:
    -   id: black-fix
        name: black (auto format)
        entry: black
        language: system
        types: [python]
        
    -   id: isort-fix
        name: isort (auto sort)
        entry: isort
        language: system
        types: [python]
        
    -   id: pytest-selenium
        name: pytest (selenium tests)
        entry: pytest
        args: ['tests/', '-k', 'selenium']
        language: system
        pass_filenames: false
        
    -   id: pytest-non-selenium
        name: pytest (non-selenium tests)
        entry: pytest
        args: ['tests/', '-k', 'not selenium']
        language: system
        pass_filenames: false

    -   id: black
        name: black
        entry: black
        language: system
        types: [python]

    -   id: isort
        name: isort
        entry: isort
        language: system
        types: [python]

    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]

    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
