repos:
-   repo: local
    hooks:
    -   id: pytest
        name: Run Pytest
        entry: ./env/Scripts/pytest.exe
        args: ['tests/', '--webdriver', 'Firefox']
        language: system
        pass_filenames: false
